# Generated by Django 5.0.6 on 2024-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor_family', models.CharField(blank=True, max_length=100, null=True)),
                ('processor_details', models.CharField(blank=True, max_length=255, null=True)),
                ('graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('internal_drive', models.CharField(blank=True, max_length=100, null=True)),
                ('display_size', models.CharField(max_length=100)),
                ('display_details', models.CharField(blank=True, max_length=255, null=True)),
                ('security_software_license', models.CharField(blank=True, max_length=255, null=True)),
                ('ports', models.CharField(blank=True, max_length=255, null=True)),
                ('expansion_slots', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_features', models.CharField(blank=True, max_length=255, null=True)),
                ('webcam_details', models.CharField(blank=True, max_length=255, null=True)),
                ('keyboard_features', models.CharField(blank=True, max_length=255, null=True)),
                ('pointing_device', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=100, null=True)),
                ('wwan', models.CharField(blank=True, max_length=100, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_efficiency', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('support_service', models.CharField(blank=True, max_length=255, null=True)),
                ('software_included', models.CharField(blank=True, max_length=255, null=True)),
                ('manageability_features', models.CharField(blank=True, max_length=255, null=True)),
                ('security_management', models.CharField(blank=True, max_length=255, null=True)),
                ('sustainable_impact', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
