# Generated by Django 5.0.6 on 2024-05-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_orderdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
